# .github/workflows/deploy-to-azure.yml

name: Deploy EliteDynamicsPro Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: EliteDynamicsFuncions
  PYTHON_VERSION: '3.11'
  FUNCTION_APP_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # environment: production

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        # cache: 'pip' # Puedes dejarlo o quitarlo, no es crítico ahora

    - name: Login via Azure Credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.FUNCTION_APP_PATH }}
        # NO app-settings aquí
        # DEJAR QUE ORYX CONSTRUYA EN AZURE (valores por defecto o explícitos)
        scm-do-build-during-deployment: true # Asegura que Oryx se ejecute
        enable-oryx-build: true              # Asegura que Oryx se ejecute

    - name: Azure logout
      run: |
        az logout
      if: always()
