# .github/workflows/deploy-to-azure.yml

name: Deploy EliteDynamicsPro Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: EliteDynamicsFuncions
  PYTHON_VERSION: '3.11' # Asegúrate que coincida con Azure
  FUNCTION_APP_PATH: '.'   # Ruta a la raíz del proyecto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # environment: production # Puedes quitarlo si usas secretos de repositorio

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip' # Buena idea mantener el caché de pip

    # --- PASO "Install dependencies" ELIMINADO ---

    - name: Login via Azure Credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Asume secreto correcto

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.FUNCTION_APP_PATH }} # Despliega desde la raíz
        python-version: ${{ env.PYTHON_VERSION }} # Informa a Azure qué versión esperar
        # NO incluimos scm-do-build-during-deployment, usa default 'true'
        app-settings: | # Asegúrate que TODOS los secretos referenciados aquí existan en GitHub
          [
            {"name": "FUNCTIONS_WORKER_RUNTIME", "value": "python", "slotSetting": false},
            {"name": "AzureWebJobsStorage", "value": "${{ secrets.AZURE_WEBJOBS_STORAGE }}", "slotSetting": false},
            {"name": "CLIENT_ID", "value": "${{ secrets.AZURE_CLIENT_ID }}", "slotSetting": false},
            {"name": "CLIENT_SECRET", "value": "${{ secrets.AZURE_CLIENT_SECRET }}", "slotSetting": true},
            {"name": "TENANT_ID", "value": "${{ secrets.AZURE_TENANT_ID }}", "slotSetting": false},
            {"name": "AZURE_SUBSCRIPTION_ID", "value": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "slotSetting": false},
            {"name": "GRAPH_SCOPE", "value": "${{ secrets.GRAPH_SCOPE || 'https://graph.microsoft.com/.default' }}", "slotSetting": false},
            {"name": "GRAPH_API_ENDPOINT", "value": "${{ secrets.GRAPH_API_ENDPOINT || 'https://graph.microsoft.com/v1.0' }}", "slotSetting": false},
            {"name": "AZURE_OPENAI_ENDPOINT", "value": "${{ secrets.AZURE_OPENAI_ENDPOINT }}", "slotSetting": false},
            {"name": "AZURE_OPENAI_API_VERSION", "value": "${{ secrets.AZURE_OPENAI_API_VERSION || '2024-02-15-preview' }}", "slotSetting": false},
            {"name": "AZURE_OPENAI_SCOPE", "value": "${{ secrets.AZURE_OPENAI_SCOPE || 'https://cognitiveservices.azure.com/.default' }}", "slotSetting": false},
            {"name": "PBI_CLIENT_ID", "value": "${{ secrets.PBI_CLIENT_ID }}", "slotSetting": false},
            {"name": "PBI_CLIENT_SECRET", "value": "${{ secrets.PBI_CLIENT_SECRET }}", "slotSetting": true},
            {"name": "PBI_TENANT_ID", "value": "${{ secrets.PBI_TENANT_ID || secrets.AZURE_TENANT_ID }}", "slotSetting": false},
            {"name": "GITHUB_PAT", "value": "${{ secrets.GITHUB_PAT }}", "slotSetting": true},
            {"name": "AZURE_CLIENT_ID_MGMT", "value": "${{ secrets.AZURE_CLIENT_ID_MGMT || secrets.AZURE_CLIENT_ID }}", "slotSetting": false},
            {"name": "AZURE_CLIENT_SECRET_MGMT", "value": "${{ secrets.AZURE_CLIENT_SECRET_MGMT || secrets.AZURE_CLIENT_SECRET }}", "slotSetting": true},
            {"name": "AZURE_RESOURCE_GROUP", "value": "${{ secrets.AZURE_RESOURCE_GROUP }}", "slotSetting": false},
            {"name": "SHAREPOINT_MEMORY_LIST_NAME", "value": "${{ secrets.SHAREPOINT_MEMORY_LIST_NAME || 'AsistenteMemoriaPersistente' }}", "slotSetting": false},
            {"name": "DEFAULT_API_TIMEOUT", "value": "${{ secrets.DEFAULT_API_TIMEOUT || '60' }}", "slotSetting": false},
            {"name": "APP_NAME", "value": "EliteDynamicsPro", "slotSetting": false},
            {"name": "DELEGATED_USER", "value": "${{ secrets.DELEGATED_USER }}", "slotSetting": false},
            {"name": "DELEGATED_PASS", "value": "${{ secrets.DELEGATED_PASS }}", "slotSetting": true}
          ]

    - name: Azure logout
      run: |
        az logout
      if: always()