# .github/workflows/deploy-to-azure.yml

name: Deploy EliteDynamicsPro Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: EliteDynamicsFuncions
  PYTHON_VERSION: '3.11'
  FUNCTION_APP_PATH: '.' # Asume que tu código está en la raíz del repo
  PYTHON_PACKAGE_PATH: '.python_packages' # Carpeta donde se instalarán las dependencias

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # environment: production

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        # cache: 'pip' # Cache opcional, puedes quitarlo para evitar warnings si no hay más pip install

    # --- PASO PARA INSTALAR DEPENDENCIAS EN .python_packages ---
    - name: Install Python dependencies
      run: |
        python -m venv ${{ env.PYTHON_PACKAGE_PATH }}
        source ${{ env.PYTHON_PACKAGE_PATH }}/bin/activate
        python -m pip install --upgrade pip
        pip install -r ${{ env.FUNCTION_APP_PATH }}/requirements.txt --target="${{ env.PYTHON_PACKAGE_PATH }}/lib/python${{ env.PYTHON_VERSION }}/site-packages"
    # ----------------------------------------------------------

    - name: Login via Azure Credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.FUNCTION_APP_PATH }} # La acción empaquetará desde aquí, incluyendo .python_packages
        # --- PARÁMETROS PARA DESACTIVAR BUILD REMOTO EN AZURE ---
        scm-do-build-during-deployment: false
        enable-oryx-build: false
        # -------------------------------------------------------------
        # NO app-settings aquí, confiamos en las que están en Azure Portal

    - name: Azure logout
      run: |
        az logout
      if: always()